# Limine Configuration File
# OS8

# Timeout before autoboot (seconds)
timeout: 3

# ==========================================
# OS8
# ==========================================

/OS8
    protocol: limine
    kernel_path: boot():/boot/bootloader.sys
