# Limine Configuration File
# OS next stage

# Timeout before autoboot (seconds)
timeout: 3

# Default boot entry
default_entry: 1

# ==========================================
# OS next stage
# ==========================================

/OS next stage
    protocol: limine
    kernel_path: boot():/boot/vibos.elf
