# Limine Configuration File
# OS next stage x64 installer ISO

timeout: 5
default_entry: 1

/OS next stage Installer
    protocol: limine
    kernel_path: boot():/boot/main.sys
    cmdline: boot=usb mode=installer

/OS next stage DOS-style Installer
    comment: BIOS-only 16-bit real-mode fallback installer
    protocol: bios
    partition: 2
