# Limine Configuration File
# OS next stage x64 installer ISO

timeout: 5
default_entry: 1

/OS next stage Graphical Installer
    protocol: limine
    kernel_path: boot():/boot/main.sys
    cmdline: boot=usb mode=installer

/OS next stage DOS Rescue Installer
    comment: BIOS-only fallback installer, separate from the graphical installer path
    protocol: bios_chainload
    partition: 2
