# Limine Configuration File
# OS next stage x64 installer ISO

timeout: 5
default_entry: 1

/OS next stage Graphical Installer
    protocol: limine
    kernel_path: boot():/boot/main.sys
    cmdline: boot=usb mode=installer
