# Limine Configuration File
# OS next stage x64

# Timeout before autoboot (seconds)
timeout: 0

# ==========================================
# OS next stage x64
# ==========================================

/OS next stage
    protocol: limine
    kernel_path: boot():/boot/main.sys
