# OS8 Boot Configuration
# OS8 x64

# Timeout before autoboot (seconds)
timeout: 0

# ==========================================
# OS8 x64
# ==========================================

/OS8
    protocol: limine
    kernel_path: boot():/boot/main.sys
    cmdline: boot=cd livecd
