#!/usr/bin/env python3
import os
import sys


ASSETS = [
    ("installer_payload_bootx64_efi", "vib-os-x86_64/limine/bin/BOOTX64.EFI"),
    ("installer_payload_limine_bios_sys", "vib-os-x86_64/limine/bin/limine-bios.sys"),
    ("installer_payload_limine_bios_cd_bin", "vib-os-x86_64/limine/bin/limine-bios-cd.bin"),
    ("installer_payload_limine_uefi_cd_bin", "vib-os-x86_64/limine/bin/limine-uefi-cd.bin"),
]


def write_bytes_array(out_c, symbol, data):
    out_c.write(f"const unsigned char {symbol}[] = {{\n")
    for i, byte in enumerate(data):
        out_c.write(f"0x{byte:02x},")
        if (i + 1) % 16 == 0:
            out_c.write("\n")
    if data and len(data) % 16 != 0:
        out_c.write("\n")
    out_c.write("};\n")
    out_c.write(f"const unsigned int {symbol}_len = {len(data)};\n\n")


def main():
    if len(sys.argv) != 3:
        print("Usage: embed_installer_payload.py <repo_root> <generated_dir>")
        return 1

    repo_root = sys.argv[1]
    generated_dir = sys.argv[2]
    os.makedirs(generated_dir, exist_ok=True)

    c_path = os.path.join(generated_dir, "installer_payload.c")
    h_path = os.path.join(generated_dir, "installer_payload.h")

    with open(c_path, "w", encoding="utf-8") as out_c, open(
        h_path, "w", encoding="utf-8"
    ) as out_h:
        out_c.write("/* Auto-generated by embed_installer_payload.py */\n\n")
        out_h.write(
            "/* Auto-generated by embed_installer_payload.py */\n\n"
            "#ifndef INSTALLER_PAYLOAD_H\n"
            "#define INSTALLER_PAYLOAD_H\n\n"
        )

        for symbol, rel_path in ASSETS:
            path = os.path.join(repo_root, rel_path)
            with open(path, "rb") as src:
                data = src.read()
            out_c.write(f"/* {rel_path} ({len(data)} bytes) */\n")
            write_bytes_array(out_c, symbol, data)
            out_h.write(f"extern const unsigned char {symbol}[];\n")
            out_h.write(f"extern const unsigned int {symbol}_len;\n")

        out_h.write("\n#endif\n")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
